<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"><head><title>Expert (async_kernel.Async_kernel.Monitor.Expert)</title><link rel="stylesheet" href="../../../../odoc.css"/><meta charset="utf-8"/><meta name="generator" content="odoc 2.1.0"/><meta name="viewport" content="width=device-width,initial-scale=1.0"/><script src="../../../../highlight.pack.js"></script><script>hljs.initHighlightingOnLoad();</script></head><body class="odoc"><nav class="odoc-nav"><a href="../index.html">Up</a> â€“ <a href="../../../index.html">async_kernel</a> &#x00BB; <a href="../../index.html">Async_kernel</a> &#x00BB; <a href="../index.html">Monitor</a> &#x00BB; Expert</nav><header class="odoc-preamble"><h1>Module <code><span>Monitor.Expert</span></code></h1></header><div class="odoc-content"><div class="odoc-spec"><div class="spec value" id="val-try_with_log_exn" class="anchored"><a href="#val-try_with_log_exn" class="anchor"></a><code><span><span class="keyword">val</span> try_with_log_exn : <span><span>( <span>exn <span class="arrow">&#45;&gt;</span></span> unit )</span> <a href="../../../../core/Core/index.html#type-ref">Core.ref</a></span></span></code></div><div class="spec-doc"><p><code>try_with_log_exn</code> is called by <code>try_with</code> when an exception is raised to a <code>try_with</code> that already returned. <code>Async_unix</code> sets it to a function that logs.</p></div></div></div></body></html>